version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=password_manager
      - JWT_SECRET=secretkey
      - PORT=8080
      - ENCRYPTION_SECRET_KEY=759c4d948c175b9ae1ddf51e29ef594cbf13443abd0a8572e4449264a7fe925f
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    command: npm run dev
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=password_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
